services:

  mysql:
    image: mysql:lts
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: humuson
      MYSQL_USER: humuson
      MYSQL_PASSWORD: humuson1234
      MYSQL_ROOT_PASSWORD: humuson1234
    networks:
      - local-bridge

networks:
  local-bridge:
    driver: bridge